### PR TITLE
fix: switch network managed

### LINKED ISSUE #2371: Switching network in custodial, then going to managed wallet doesn't set the network of managed wallet
## Why

How to reproduce:
- In prod: with a custodial wallet connected, switch network from mainnet to sandbox in the app settings
- Then swtich from custodial to managed wallet and it should use the sandbox settings instead of mainnet

## How

Automatically switch to the current managed wallet network when switching from custodial to managed

### PR DESCRIPTION
**Pull request by baktun14**
closes #2371 

## Summary by CodeRabbit

* **Bug Fixes**
  * Strengthened network validation for managed wallets: the app now enforces the configured managed network and redirects to the home page if it doesn't match the current network to prevent misconfiguration.
* **Other**
  * Transaction links now point to the updated stats app URL to ensure correct transaction detail routing.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: apps/deploy-web/src/context/WalletProvider/WalletProvider.tsx [hunk 1]
```diff
@@ -136,6 +135,13 @@ export const WalletProvider: React.FC<{ children: React.ReactNode }> = ({ childr
     setSettingsId(walletAddress || null);
   }, [walletAddress]);
 
+  useEffect(() => {
+    if (selectedWalletType === "managed" && selectedNetworkId !== appConfig.NEXT_PUBLIC_MANAGED_WALLET_NETWORK_ID) {
+      setSelectedNetworkId(appConfig.NEXT_PUBLIC_MANAGED_WALLET_NETWORK_ID);
+      window.location.href = UrlService.home();
```
Comment (stalniy) [inline apps/deploy-web/src/context/WalletProvider/WalletProvider.tsx]: **suggestion(blocking):** please use `windowLocation` and `urlService` from DI (ie., useServices)

**Review by stalniy — CHANGES_REQUESTED** [review]

File: apps/deploy-web/src/context/WalletProvider/WalletProvider.tsx (hunk 1 above)
Comment (baktun14) [reply apps/deploy-web/src/context/WalletProvider/WalletProvider.tsx]: Didn't know we had windowLocation in there, I'll keep di more in mind for the future

**Review by stalniy — APPROVED** [review]
