### PR TITLE
Min AKT and minor bug fixes

### LINKED ISSUE #581: Add additional provider attributes to Console Provider
When setting up the provider, some attributes are missing.

Missing attributes:
host: <value>
organization: <value>

Also missing info section:
email: <vakue>
website: <value>

These are standard Akash attributes, which are mandatory for any provider to pass an audit. Setting them up by default would save the team a lot of time.

Example:
- key: host
  value: akash
- key: tier
  value: community
- key: organization
  value: organization_name
host_uri: https://eample.com:8443
info:
  email: eample.com@gmail.com
  website: www.eample.com
owner: akash****

### LINKED ISSUE #625: Reduce min AKT requirement
- We need to reduce the amount of AKT required to become a provider from 30 to 5 or 10 AKT.
- This change will help smaller providers to test out and also support 10 leases with reduced 0.5 akt per lease.

### PR DESCRIPTION
**Pull request by jigar-arc10**
- Popup for minimum AKT requirement for becoming the Provider
- added default attribute
- Control node and Worker Node information panel
- fixed activity logs in URL
- fixed type issues
- other minor fixes

### CODE REVIEW

File: apps/provider-console/src/components/become-provider/ServerAccess.tsx [hunk 1]
```diff
@@ -1,17 +1,39 @@
...
+
 export const ServerAccess: React.FC<ServerAccessProps> = ({ onComplete }) => {
   const [numberOfServers, setNumberOfServers] = useState(1);
   const [activateServerForm, setActivateServerForm] = useState(false);
   const [currentServer, setCurrentServer] = useState(0);
+  const [showBalancePopup, setShowBalancePopup] = useState(false);
+  const [showNodeDistribution, setShowNodeDistribution] = useState(false);
+
+  const { walletBalances } = useWallet();
+  const hasEnoughBalance = (walletBalances?.uakt || 0) >= 30000000;
```
Comment (baktun14) [inline apps/provider-console/src/components/become-provider/ServerAccess.tsx]: `const MIN_BALANCE = 30_000_000;`

File: apps/provider-console/src/components/become-provider/ServerAccess.tsx [hunk 2]
```diff
@@ -50,13 +119,75 @@ export const ServerAccess: React.FC<ServerAccessProps> = ({ onComplete }) => {
...
+          </div>
         </div>
       ) : (
-        <ServerForm key={currentServer} currentServerNumber={currentServer} onComplete={handleServerFormSubmit} />
+        <ServerForm
+          key={currentServer}
+          currentServerNumber={currentServer}
+          onComplete={handleServerFormSubmit}
+          isControlPlane={getCurrentServerType(currentServer).isControlPlane}
+          nodeNumber={getCurrentServerType(currentServer).nodeNumber}
```
Comment (baktun14) [inline apps/provider-console/src/components/become-provider/ServerAccess.tsx]: this function could be called just once

File: apps/provider-console/src/pages/settings/index.tsx [hunk 3]
```diff
@@ -12,25 +12,35 @@ import restClient from "@src/utils/restClient";
 import { sanitizeMachineAccess } from "@src/utils/sanityUtils";
 import { stripProviderPrefixAndPort } from "@src/utils/urlUtils";
 
-const urlSchema = z.string().url();
+const urlSchema = z.string().refine(value => {
```
Comment (baktun14) [inline apps/provider-console/src/pages/settings/index.tsx:15]: `z.string().url();` doesn't work?

**Review by baktun14 — DISMISSED** [review]

File: apps/provider-console/src/pages/settings/index.tsx (hunk 3 above)
Comment (jigar-arc10) [reply apps/provider-console/src/pages/settings/index.tsx:15]: We need a URL without www, http or https, just plane example.com likea  URL

File: apps/provider-console/src/components/become-provider/ServerAccess.tsx [hunk 4]
```diff
@@ -27,7 +27,8 @@ export const ServerAccess: React.FC<ServerAccessProps> = ({ onComplete }) => {
   const [showNodeDistribution, setShowNodeDistribution] = useState(false);
 
   const { walletBalances } = useWallet();
-  const hasEnoughBalance = (walletBalances?.uakt || 0) >= 30000000;
+  const MIN_BALANCE = 5_000_000;
```
Comment (baktun14) [inline apps/provider-console/src/components/become-provider/ServerAccess.tsx:30]: It's not supposed to be 30 AKT?

Comment (jigar-arc10) [reply apps/provider-console/src/components/become-provider/ServerAccess.tsx:30]: Providers from the community complained about 30AKT in closed testing, so we reduced it to 5 AKT, as currently only 0.5 is deposited to bid, so it should be okay.

Comment (baktun14) [reply apps/provider-console/src/components/become-provider/ServerAccess.tsx:30]: Okay

**Review by baktun14 — APPROVED** [review]
