### PR TITLE
fix(provider): added missing types and added error handling

### LINKED ISSUE #705: Client Error when the user tries to import a different wallet from the one connected to the browser plugin
A couple of providers experienced client error issues when they tried to create a provider multiple times with the same wallet.
This error happens during the last step of provider creation.

Initial assessment - Local storage corruption happened due to multiple provider creation processes. We need more testing to find the root cause.

### PR DESCRIPTION
**Pull request by jigar-arc10**
- fixed missing types in queries
- fixed error-handling issues
- added toast shadcn component

### CODE REVIEW

File: packages/ui/components/toast.tsx [hunk 1]
```diff
@@ -0,0 +1,95 @@
+"use client";
```
Comment (baktun14) [inline packages/ui/components/toast.tsx:1]: We use `notistack` for toasts in deploy-web. I removed the this shadcn component in the beginning because notistack had a better api I think, I'm not 100% sure. We can leave it like for now for efficiency, but let's keep it in mind.

**Review by baktun14 — APPROVED** [review]

File: packages/ui/components/toast.tsx (hunk 1 above)
Comment (jigar-arc10) [reply packages/ui/components/toast.tsx:1]: Sure, I will put an issue for change to notistack in future for the provider console.
