### PR TITLE
Fix/provider console/ga prep

### LINKED ISSUE #838: Control Node not connected - "Not-a-number" error shows in pricing page.

### LINKED ISSUE #839: Activity Logs should have better Error for non console providers

### LINKED ISSUE #840: Change titles in provider console
"Competitive Pricing Insights" -> "Comparative Pricing Insights"
"Monthly Cost" -> "Monthly Earnings"

### LINKED ISSUE #841: Add error message in pricing page for Heterogeneous GPUs

### PR DESCRIPTION
**Pull request by jigar-arc10**
closes #841 , #840 , #839 , #838

### CODE REVIEW

File: apps/provider-console/src/components/become-provider/ProviderPricing.tsx [hunk 1]
```diff
@@ -99,6 +100,7 @@ export const ProviderPricing: React.FC<ProviderPricingProps> = ({ onComplete, ed
         });
       } else if (providerDetails) {
         const { activeStats, pendingStats, availableStats } = providerDetails;
+        console.log("activeStats", activeStats);
```
Comment (baktun14) [inline apps/provider-console/src/components/become-provider/ProviderPricing.tsx]: ✂️

Comment (jigar-arc10) [reply apps/provider-console/src/components/become-provider/ProviderPricing.tsx]: removed

**Review by baktun14 — APPROVED** [review]
