### PR TITLE
fix(provider): render longer provider names, make them copiable

### LINKED ISSUE #858: Increase displayed provider hostname to 40 characters
## Problem Statement

Customers/ Users of Console frequently report issues with deployments and must provider hostnames of the provider that the deployment is running on. Unfortunately because Console truncates the provider hostname, most of the GPU providers (that start with "provider" and end with "akash.pub" end up looking the same (as shown below) in the deployments list as well in the deployment details page

Image

Image

## Solution
I'd suggesting making some or all of these changes to the UI ( @aktdenis - your thoughts on solving this UI issue?)
1. Increase displayed hostname field to allow for up to 40 characters if possible. This would cover the longest of the GPU hostnames we have today - which is `provider.rtx4090.evergreen.akash.pub`
2. Include a "copy" UI function to allow the user to just copy it to the clipboard.
3. Do the above things for both the deployments list page as well as the deployments detail page

### PR DESCRIPTION
**Pull request by jzsfkzm**
closes #858

### CODE REVIEW

**Review by baktun14 — DISMISSED** [review]
Nice!🔥 Can you just post a quick screenshot of how it looks like please?

File: apps/deploy-web/src/components/deployments/LeaseChip.tsx [hunk 1]
```diff
@@ -27,25 +28,24 @@ export const LeaseChip: React.FunctionComponent<Props> = ({ lease, providers })
...
+        {providerName ? (
+          <ShortenedValue value={providerName} maxLength={40} headLength={14} />
+        ) : (
+          <Spinner size="xSmall" />
+        )}
         <StatusPill state={lease.state} size="small" />
       </Badge>
     </Link>
+
+    {providerName && <CopyTextToClipboardButton value={providerName} />}
```
Comment (baktun14) [inline apps/deploy-web/src/components/deployments/LeaseChip.tsx:48]: Is that shown as just an empty button?

**Comment by jzsfkzm** [comment]
> Nice!🔥 Can you just post a quick screenshot of how it looks like please?

Thanks, sure, here you are @baktun14. Somewhat played around with col widths on this table, all those had the same width, now some columns are wider:
Screenshot 2025-02-24 at 0 18 03

Added it here too:
Screenshot 2025-02-24 at 0 19 01

And here as well, also changed the icon next to URIs:
Screenshot 2025-02-24 at 0 20 56

**Review by baktun14 — APPROVED** [review]
