### PR TITLE
fix: drop deprecated prop so no JS error is shown

### LINKED ISSUE #2105: Unselecting service in logs causes runtime exception
## What

1. Authenticate in console
2. Create any deployment
3. Go to logs
4. Unselect all services in log filter

## Expected result

Empty logs section, loading is stopped

## Actual result

Empty logs section, loading bar never stops

## Additional

This happens because of runtime error

https://github.com/user-attachments/assets/49179b4c-52f9-4513-a7e1-27dfab06f023

### PR DESCRIPTION
**Pull request by jzsfkzm**
closes #2105

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed menu anchoring for select-style checkboxes so dropdowns now rely on default anchoring. This improves dropdown positioning and visual alignment across different layouts and screen sizes, reducing occasional misplacement of menu content.

### CODE REVIEW

File: apps/deploy-web/src/components/shared/SelectCheckbox.tsx [hunk 1]
```diff
@@ -17,7 +17,6 @@ const MenuProps = {
       width: 250
     }
   },
-  getContentAnchorEl: null,
```
Comment (stalniy) [inline apps/deploy-web/src/components/shared/SelectCheckbox.tsx:20]: **question(blocking):** @jzsfkzm could you please explain a bit why we need to remove it? I looked into MenuProps and I don't see this property but there is `anchorEl`. Should we use it instead?

**Review by stalniy — CHANGES_REQUESTED** [review]

File: apps/deploy-web/src/components/shared/SelectCheckbox.tsx (hunk 1 above)
Comment (jzsfkzm) [reply apps/deploy-web/src/components/shared/SelectCheckbox.tsx:20]: > **question(blocking):** @jzsfkzm could you please explain a bit why we need to remove it? I looked into MenuProps and I don't see this property but there is `anchorEl`. Should we use it instead?

Sure! With this prop being present, when you click the `Select` for selecting services, there's a JS warning thrown in Developer Console:
Screenshot 2025-11-17 at 11 08 23
This is not showing in prod for some reason though. Anyway, [docs for 5.x suggest just to remove the prop](https://v5.mui.com/material-ui/migration/v5-component-changes/#remove-getcontentanchorel-prop), and `anchorOrigin` and `transformOrigin` are well enough for positioning the menu.

**Review by stalniy — APPROVED** [review]
