### PR TITLE
fix: checkbox can optionally have a larger clickable wrapper

### LINKED ISSUE #1981: Lists checkboxes clickable area is too small
When trying it check a deployment it's easy to miss the checkbox causing navigation to a different page. It's caused by 2 potential issues:
- checkboxes are too small
- clickable area around checkboxes is too small

Fixing this would improve UX for this action.

### PR DESCRIPTION
**Pull request by jzsfkzm**
useful when the wrapping element is clickable too (eg. in lists)

closes #1981

## Summary by CodeRabbit

* **New Features**
  * Checkboxes now support an optional expanded touch target to improve accessibility and ease of use on mobile and touchscreens.
  * Deployment list rows now enable the expanded touch target for selectable items, making selection easier on touch devices.

### CODE REVIEW

File: apps/deploy-web/src/components/deployments/DeploymentListRow.tsx [hunk 1]
```diff
@@ -294,6 +294,7 @@ export const DeploymentListRow: React.FunctionComponent<Props> = ({ deployment,
             {isSelectable && (
               <Checkbox
                 checked={checked}
+                expandedTouchTarget={true}
```
Comment (ygrishajev) [inline apps/deploy-web/src/components/deployments/DeploymentListRow.tsx:297]: non-blocking 

```suggestion
                expandedTouchTarget
```

File: packages/ui/components/checkbox.tsx [hunk 2]
```diff
@@ -5,31 +5,59 @@ import { Check } from "lucide-react";
...
+const Checkbox = React.forwardRef<
+  React.ElementRef<typeof CheckboxPrimitive.Root>,
+  React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root> & CheckboxTouchTargetProps
+>(({ className, onClick, expandedTouchTarget = false, ...props }, ref) => {
+  const checkboxRef = React.useRef<HTMLButtonElement>(null);
+  const wrapperRef = React.useRef<HTMLDivElement>(null);
+
+  React.useImperativeHandle(ref, () => checkboxRef.current!);
+
+  const handleWrapperClick = (e: React.MouseEvent<HTMLDivElement>) => {
```
Comment (ygrishajev) [inline packages/ui/components/checkbox.tsx]: could you call is smth like
```suggestion
  const triggerCheckboxClick = (e: React.MouseEvent<HTMLDivElement>) => {
```

just to make the code a bit more readable

File: apps/deploy-web/src/components/deployments/DeploymentListRow.tsx (hunk 1 above)
Comment (ygrishajev) [reply apps/deploy-web/src/components/deployments/DeploymentListRow.tsx:297]: do I get it right, that this prop exist to not break some other existing UI?

Comment (jzsfkzm) [reply apps/deploy-web/src/components/deployments/DeploymentListRow.tsx:297]: Yes, we have checkboxes at several places, and I saw it as a risky change just adding this margin. Should we check all the occurrences?

Comment (ygrishajev) [reply apps/deploy-web/src/components/deployments/DeploymentListRow.tsx:297]: I think this is fine

**Review by ygrishajev — APPROVED** [review]
