### PR TITLE
fix: invalidate deployment when toggling alert status

### LINKED ISSUE #1768: Alert Enabled state not in sync between Deployment details and Alerts pages
Steps to reproduce:
1. Setup a deployment and enable the Escrow alert
2. Nav to the Alerts page
3. Disable the Escrow alert within the table - Success banner is displayed
4. Nav to the deployment details page.
5. Displays the Save button as active and Escrow alert still enabled.

https://github.com/user-attachments/assets/ffdf7bf5-ba40-4ace-a5be-378fb7f10ee9

### PR DESCRIPTION
**Pull request by jzsfkzm**
closes #1768

## Summary by CodeRabbit

- **Bug Fixes**
  - Deployment details now refresh immediately after enabling or disabling an alert, preventing stale information.
  - Alert toggles reliably update related deployment data without requiring manual refresh or navigation.

- **New Features**
  - Alert toggles can optionally be tied to a specific deployment sequence so related deployment info updates correctly and stays in sync.

### CODE REVIEW

File: apps/deploy-web/src/components/alerts/AlertsListContainer/AlertsListContainer.tsx [hunk 1]
```diff
@@ -92,6 +94,10 @@ export const AlertsListContainer: FC<AlertsListContainerProps> = ({ children })
         });
         notificator.success(`Alert ${enabled ? "enabled" : "disabled"}`);
         refetch();
+
+        await queryClient.invalidateQueries({
+          queryKey: ["DEPLOYMENT_DETAIL"]
```
Comment (baktun14) [inline apps/deploy-web/src/components/alerts/AlertsListContainer/AlertsListContainer.tsx]: suggestion: we have a query keys object and it includes the address and dseq `static getDeploymentDetailKey = (address: string, dseq: string) => ["DEPLOYMENT_DETAIL", address, dseq];`

Comment (jzsfkzm) [reply apps/deploy-web/src/components/alerts/AlertsListContainer/AlertsListContainer.tsx]: `dseq` is not always available (as per types), that's why I took this shortcut at the first attempt. But you're right, better off using the central object, changed it now.

**Review by baktun14 — APPROVED** [review]
